version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exec_engine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  compilers:
    build:
      context: ./compilers
      dockerfile: Dockerfile
    volumes:
      - compilers-volume:/opt/compilers
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - compilers
    volumes:
      - compilers-volume:/opt/compilers
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: exec_engine
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      SECRET_KEY: your_secret_key_here
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      MAX_CONCURRENT_SUBMISSIONS: 5
  
volumes:
  postgres_data:
  compilers-volume:
