services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exec_engine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    image: execengine-api:latest
    privileged: true
    tty: true
    restart: always
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8000:8000"
    volumes:
      - ./execengine.ini:/execengine.ini:ro
    environment:
      RABBITMQ_HOST: rabbitmq


volumes:
  postgres_data:
  rabbitmq_data:

